(function(){
  'use strict';let api='',token='',rows=[];
  const $=s=>document.querySelector(s),show=id=>['connect','setup','login','dashboard'].forEach(x=>$('#'+x).hidden=x!==id);
  function setApi(v){api=v.replace(/\/$/,'');localStorage.setItem('opt1_api_url',api);$('#apiUrl').value=api;}
  async function req(path,opt={}){opt.headers=Object.assign({'Content-Type':'application/json'},opt.headers||{});if(token)opt.headers.Authorization='Bearer '+token;const r=await fetch(api+path,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Error de conexión');return d;}
  async function connect(){const f=$('#connectFeedback');try{setApi($('#apiUrl').value.trim());f.textContent='Conectando...';const d=await req('/api/setup-status');f.textContent='';show(d.needsSetup?'setup':'login');}catch(e){f.textContent=e.message;f.className='feedback no';}}
  $('#connectBtn').onclick=connect;$('#apiUrl').value=localStorage.getItem('opt1_api_url')||window.OPT_CONFIG.API_URL||'';
  $('#setupForm').onsubmit=async e=>{e.preventDefault();const f=e.target.parentElement.querySelector('.feedback'),d=new FormData(e.target);try{const r=await req('/api/setup',{method:'POST',body:JSON.stringify({username:d.get('username'),password:d.get('password')})});token=r.token;localStorage.setItem('opt1_admin_token',token);openDashboard();}catch(x){f.textContent=x.message;f.className='feedback no';}};
  $('#adminLogin').onsubmit=async e=>{e.preventDefault();const f=e.target.parentElement.querySelector('.feedback'),d=new FormData(e.target);try{const r=await req('/api/login',{method:'POST',body:JSON.stringify({role:'admin',username:d.get('username'),password:d.get('password')})});token=r.token;localStorage.setItem('opt1_admin_token',token);openDashboard();}catch(x){f.textContent=x.message;f.className='feedback no';}};
  async function openDashboard(){show('dashboard');$('#logout').hidden=false;await load();}
  async function load(){const d=await req('/api/admin/students');rows=d.students;const groups=[...new Set(rows.map(r=>r.groupName))];$('#groupFilter').innerHTML='<option value="">Todos</option>'+groups.map(g=>'<option>'+escapeHtml(g)+'</option>').join('');render();}
  function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function render(){const q=$('#search').value.toLowerCase(),g=$('#groupFilter').value,st=$('#statusFilter').value;const data=rows.filter(r=>{const rowStatus=r.status||'none';return(!q||[r.code,r.firstName,r.lastName,r.groupName].join(' ').toLowerCase().includes(q))&&(!g||r.groupName===g)&&(!st||rowStatus===st);});$('#summary').textContent=rows.length+' alumnos registrados · '+rows.filter(r=>r.status==='passed').length+' han superado la unidad';$('#students').innerHTML=data.map(r=>{const status=r.status||'none',label={passed:'Superado',failed:'No superado',incomplete:'En curso',none:'Sin iniciar'}[status];return'<tr><td><b>'+escapeHtml(r.code)+'</b></td><td>'+escapeHtml(r.lastName+', '+r.firstName)+'</td><td>'+escapeHtml(r.groupName)+'</td><td>'+(r.score??0)+' %</td><td><span class="status '+status+'">'+label+'</span></td><td>'+escapeHtml(r.lastLogin?new Date(r.lastLogin).toLocaleString('es-ES'):'—')+'</td><td><button class="mini" data-reset="'+r.id+'">PIN 1234</button></td></tr>';}).join('');document.querySelectorAll('[data-reset]').forEach(b=>b.onclick=async()=>{if(confirm('¿Restablecer el PIN de este alumno a 1234?')){await req('/api/admin/students/'+b.dataset.reset+'/reset-pin',{method:'POST',body:JSON.stringify({pin:'1234'})});alert('PIN restablecido.');}});}
  $('#search').oninput=render;$('#groupFilter').onchange=render;$('#statusFilter').onchange=render;$('#refresh').onclick=load;$('#logout').onclick=()=>{localStorage.removeItem('opt1_admin_token');location.reload();};
  $('#export').onclick=async()=>{const r=await fetch(api+'/api/admin/export.csv',{headers:{Authorization:'Bearer '+token}});if(!r.ok)return alert('No se pudo exportar.');const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='progreso-opt1.csv';a.click();URL.revokeObjectURL(a.href);};
  (async()=>{api=$('#apiUrl').value.replace(/\/$/,'');token=localStorage.getItem('opt1_admin_token')||'';if(api&&token){try{await req('/api/me');return openDashboard();}catch{localStorage.removeItem('opt1_admin_token');}}show('connect');})();
})();
