(function(){
  'use strict';
  var api=null, state={done:[],practice:{},portfolio:{},examStarted:false,examDone:false,score:0,current:'home'};
  function findAPI(win){var tries=0;while(win&&tries<10){if(win.API)return win.API;win=win.parent;tries++;}try{if(window.opener)return findAPI(window.opener);}catch(e){}return null;}
  function scormGet(k){try{return api?api.LMSGetValue(k):'';}catch(e){return '';}}
  function scormSet(k,v){try{if(api)api.LMSSetValue(k,String(v));}catch(e){}}
  var remoteTimer=null;
  function commit(){try{localStorage.setItem('sa_ud1_state',JSON.stringify(state));}catch(e){}if(api){scormSet('cmi.suspend_data',JSON.stringify(state));scormSet('cmi.core.lesson_location',state.current);api.LMSCommit('');}else if(window.RemoteStore&&RemoteStore.getProfile()){clearTimeout(remoteTimer);remoteTimer=setTimeout(function(){RemoteStore.saveProgress(state).catch(function(){});},500);}}
  async function init(){api=findAPI(window);if(api){try{api.LMSInitialize('');}catch(e){}var raw=scormGet('cmi.suspend_data');if(raw)try{state=Object.assign(state,JSON.parse(raw));}catch(e){}var n=scormGet('cmi.core.student_name');if(n)document.getElementById('studentName').textContent=n;var status=scormGet('cmi.core.lesson_status');if(!status||status==='not attempted')scormSet('cmi.core.lesson_status','incomplete');}else if(window.RemoteStore){var p=await RemoteStore.requireAuth();document.getElementById('studentName').textContent=p.firstName+' '+p.lastName+' · '+p.code;try{var remote=await RemoteStore.loadProgress();if(remote&&remote.state)state=Object.assign(state,remote.state);}catch(e){try{var l=localStorage.getItem('sa_ud1_state');if(l)state=Object.assign(state,JSON.parse(l));}catch(x){}}}else{try{var l=localStorage.getItem('sa_ud1_state');if(l)state=Object.assign(state,JSON.parse(l));}catch(e){}}render();show(state.current||'home');}
  function render(){document.querySelectorAll('.nav-item').forEach(function(b){var v=b.dataset.view;if(/^m\d$/.test(v)){var m=Number(v.slice(1)),unlocked=m===1||state.done.indexOf(m-1)>=0;b.classList.toggle('locked',!unlocked);b.classList.toggle('done',state.done.indexOf(m)>=0);}if(v==='final'){b.classList.toggle('locked',state.done.length<6);b.classList.toggle('done',state.examDone&&state.score>=70);}});var pct=Math.round((state.done.length/6)*80+(state.examDone?20:0));document.getElementById('progressBar').style.width=pct+'%';document.getElementById('progressText').textContent=pct+' %';renderPortfolio();renderExamStatus();}
  function show(id){var btn=document.querySelector('.nav-item[data-view="'+id+'"]');if(btn&&btn.classList.contains('locked'))return;document.querySelectorAll('.view').forEach(function(v){v.classList.toggle('active',v.id===id);});document.querySelectorAll('.nav-item').forEach(function(b){b.classList.toggle('active',b.dataset.view===id);});state.current=id;commit();document.getElementById('contenido').focus();window.scrollTo(0,0);}
  document.addEventListener('click',function(e){var nav=e.target.closest('.nav-item');if(nav){show(nav.dataset.view);return;}var go=e.target.closest('.go');if(go){show(go.dataset.target);return;}var opt=e.target.closest('.options button');if(opt){var box=opt.closest('.practice');if((state.practice[box.dataset.id]||0)>=3)return;box.querySelectorAll('button').forEach(function(b){b.classList.remove('selected');});opt.classList.add('selected');checkPractice(box,opt.dataset.value);return;}var check=e.target.closest('.check-input');if(check){var box=check.closest('.practice'),input=box.querySelector('input');checkPractice(box,input.value.trim());return;}var comp=e.target.closest('.complete');if(comp){completeMission(Number(comp.dataset.mission),comp);return;}});
  function checkPractice(box,value){var id=box.dataset.id,tries=state.practice[id]||0,fb=box.querySelector('.feedback');if(value===box.dataset.answer){state.practice[id]='ok';fb.textContent='Correcto. Ya puedes completar la misión.';fb.className='feedback ok';box.dataset.passed='true';}else{tries++;state.practice[id]=tries;fb.className='feedback no';fb.textContent=tries<3?'Todavía no. Revisa el ejemplo y vuelve a intentarlo. Intento '+tries+' de 3.':'Solución: '+solution(id)+' Repasa la explicación antes de continuar.';if(tries>=3)box.dataset.passed='true';}commit();}
  function solution(id){return({p1:'Los cartuchos son consumibles.',p2:'Las cajas pesadas se colocan abajo.',p3:'12 − 15 = −3.',p4:'3 × 4 + 2 = 14.',p5:'El proveedor B entrega en dos días y ofrece buena calidad.',p6:'Se anota la falta y se reclama.'})[id]||'';}
  function completeMission(m,btn){var box=document.querySelector('#m'+m+' .practice');if(box.dataset.passed!=='true'){var fb=box.querySelector('.feedback');fb.textContent='Completa primero la práctica guiada.';fb.className='feedback no';return;}if(state.done.indexOf(m)<0)state.done.push(m);state.done.sort();commit();render();if(m<6)show('m'+(m+1));else show('portfolio');}
  var portfolioItems=['Clasificación y códigos','Plano y normas de almacén','Inventario y desviaciones','Cálculo del punto de pedido','Propuesta de compra','Recepción e incidencia'];
  function renderPortfolio(){var root=document.getElementById('portfolioFields');if(root.children.length)return;portfolioItems.forEach(function(t,i){var d=document.createElement('div');d.className='portfolio-card';d.innerHTML='<h3>'+(i+1)+' '+t+'</h3><textarea aria-label="'+t+'" placeholder="Escribe aquí tu borrador..."></textarea>';var ta=d.querySelector('textarea');ta.value=state.portfolio[i]||'';ta.addEventListener('input',function(){state.portfolio[i]=ta.value;commit();});root.appendChild(d);});}
  var questions=[
    ['¿Qué artículo es un consumible?',['Archivador metálico','Cartucho de tóner','Mesa auxiliar'],1],
    ['¿Qué característica debe tener un código?',['Ser único','Ser muy largo','Cambiar cada semana'],0],
    ['¿Dónde se coloca una caja pesada?',['Balda alta','Suelo del pasillo','Balda baja'],2],
    ['¿Cómo se calcula una desviación?',['Real menos registrado','Registrado más real','Precio por cantidad'],0],
    ['Sistema 20 y recuento 18. ¿Diferencia?',['+2','−2','38'],1],
    ['¿Para qué sirve el stock de seguridad?',['Para decorar el almacén','Para cubrir imprevistos','Para aumentar el precio'],1],
    ['Consumo 2 por semana, plazo 3 semanas y seguridad 1. ¿Punto de pedido?',['5','6','7'],2],
    ['¿Qué debe incluir una propuesta de pedido?',['Cantidad y motivo','Solo el nombre del proveedor','Solo el precio'],0],
    ['¿Qué se compara al recibir?',['Pedido, albarán y mercancía','Factura y nómina','Inventario y contrato'],0],
    ['Falta una caja. ¿Qué actuación es correcta?',['No decir nada','Anotar y reclamar','Modificar el pedido original'],1]
  ];
  function buildExam(){var f=document.getElementById('exam');f.innerHTML='';questions.forEach(function(q,i){var d=document.createElement('fieldset');d.className='exam-q';var h='<legend><b>'+(i+1)+'. '+q[0]+'</b></legend>';q[1].forEach(function(o,j){h+='<label><input type="radio" name="q'+i+'" value="'+j+'"> '+o+'</label>';});d.innerHTML=h;f.appendChild(d);});var b=document.createElement('button');b.type='submit';b.className='primary';b.textContent='Entregar evaluación';f.appendChild(b);f.onsubmit=gradeExam;}
  document.getElementById('startExam').addEventListener('click',function(){if(state.examDone)return;state.examStarted=true;commit();buildExam();document.getElementById('examIntro').hidden=true;document.getElementById('exam').hidden=false;if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(function(){});});
  function gradeExam(e){e.preventDefault();var correct=0,all=true;questions.forEach(function(q,i){var a=document.querySelector('input[name="q'+i+'"]:checked');if(!a)all=false;else if(Number(a.value)===q[2])correct++;});if(!all){alert('Responde las diez preguntas antes de entregar.');return;}state.score=correct*10;state.examDone=true;scormSet('cmi.core.score.raw',state.score);scormSet('cmi.core.score.min','0');scormSet('cmi.core.score.max','100');scormSet('cmi.core.lesson_status',state.score>=70?'passed':'failed');commit();renderExamStatus();render();if(document.fullscreenElement)document.exitFullscreen().catch(function(){});}
  function renderExamStatus(){var intro=document.getElementById('examIntro'),exam=document.getElementById('exam'),result=document.getElementById('result');if(state.examDone){intro.hidden=true;exam.hidden=true;result.hidden=false;result.innerHTML='<h3>'+(state.score>=70?'Unidad superada':'Unidad no superada')+'</h3><p>Calificación: <b>'+state.score+' / 100</b>.</p><p>'+(state.score>=70?'Has demostrado los aprendizajes esenciales. Completa tu dossier y entrégalo según las indicaciones del profesorado.':'Revisa las misiones y solicita la actividad de recuperación por criterios.')+'</p>';}else{result.hidden=true;}}
  document.getElementById('exitBtn').addEventListener('click',function(){commit();if(api){try{api.LMSFinish('');}catch(e){}document.getElementById('exitBtn').textContent='Progreso guardado';}else if(window.RemoteStore){setTimeout(function(){RemoteStore.logout();},700);}});
  window.addEventListener('beforeunload',function(){commit();if(api){try{api.LMSFinish('');}catch(e){}}});
  init();
})();
