(function(){
  'use strict';
  var token='', profile=null;
  function base(){var q=new URLSearchParams(location.search).get('api');if(q){localStorage.setItem('opt1_api_url',q.replace(/\/$/,''));history.replaceState({},'',location.pathname);}return(q||localStorage.getItem('opt1_api_url')||window.OPT_CONFIG.API_URL||'').replace(/\/$/,'');}
  async function request(path,options){var url=base();if(!url)throw new Error('Configura primero la dirección del servidor.');options=options||{};options.headers=Object.assign({'Content-Type':'application/json'},options.headers||{});if(token)options.headers.Authorization='Bearer '+token;var res=await fetch(url+path,options);var data=await res.json().catch(function(){return{};});if(!res.ok)throw new Error(data.error||'No se pudo conectar con el servidor.');return data;}
  function setupUI(){var gate=document.getElementById('authGate'),feedback=document.getElementById('authFeedback');document.getElementById('apiUrlInput').value=base();document.querySelectorAll('[data-auth-tab]').forEach(function(b){b.onclick=function(){document.querySelectorAll('[data-auth-tab]').forEach(function(x){x.classList.toggle('active',x===b);});document.getElementById('loginForm').hidden=b.dataset.authTab!=='login';document.getElementById('registerForm').hidden=b.dataset.authTab!=='register';feedback.textContent='';};});document.getElementById('saveApiUrl').onclick=function(){var v=document.getElementById('apiUrlInput').value.trim().replace(/\/$/,'');if(v){localStorage.setItem('opt1_api_url',v);feedback.textContent='Dirección guardada. Ya puedes registrarte o entrar.';feedback.className='feedback ok';}};document.getElementById('loginForm').onsubmit=async function(e){e.preventDefault();feedback.textContent='Comprobando acceso...';try{var fd=new FormData(e.target),d=await request('/api/login',{method:'POST',body:JSON.stringify({role:'student',code:fd.get('code').trim().toUpperCase(),pin:fd.get('pin')})});token=d.token;profile=d.profile;localStorage.setItem('opt1_token',token);gate.hidden=true;window.dispatchEvent(new CustomEvent('opt1-authenticated',{detail:profile}));}catch(err){feedback.textContent=err.message;feedback.className='feedback no';}};document.getElementById('registerForm').onsubmit=async function(e){e.preventDefault();feedback.textContent='Creando acceso...';try{var fd=new FormData(e.target),d=await request('/api/student/register',{method:'POST',body:JSON.stringify({firstName:fd.get('firstName'),lastName:fd.get('lastName'),group:fd.get('group'),pin:fd.get('pin')})});token=d.token;profile=d.profile;localStorage.setItem('opt1_token',token);feedback.innerHTML='Cuenta creada. Tu código personal es <strong>'+d.profile.code+'</strong>. Anótalo para volver a entrar.';feedback.className='feedback ok';setTimeout(function(){gate.hidden=true;window.dispatchEvent(new CustomEvent('opt1-authenticated',{detail:profile}));},2500);}catch(err){feedback.textContent=err.message;feedback.className='feedback no';}};}
  async function requireAuth(){setupUI();var stored=localStorage.getItem('opt1_token');if(stored){token=stored;try{var d=await request('/api/me');profile=d.profile;document.getElementById('authGate').hidden=true;return profile;}catch(e){localStorage.removeItem('opt1_token');token='';}}document.getElementById('authGate').hidden=false;return new Promise(function(resolve){window.addEventListener('opt1-authenticated',function(e){resolve(e.detail);},{once:true});});}
  async function loadProgress(){return request('/api/progress?courseId='+encodeURIComponent(window.OPT_CONFIG.COURSE_ID));}
  async function saveProgress(state){return request('/api/progress',{method:'PUT',body:JSON.stringify({courseId:window.OPT_CONFIG.COURSE_ID,version:window.OPT_CONFIG.COURSE_VERSION,state:state,score:state.score||0,status:state.examDone?(state.score>=70?'passed':'failed'):'incomplete'})});}
  function logout(){token='';profile=null;localStorage.removeItem('opt1_token');location.reload();}
  window.RemoteStore={requireAuth:requireAuth,loadProgress:loadProgress,saveProgress:saveProgress,logout:logout,getProfile:function(){return profile;}};
})();
